### User Creation Request
POST http://localhost:8080/clinic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aGFwcC1jMWY4NiIsImF1ZCI6ImF1dGhhcHAtYzFmODYiLCJhdXRoX3RpbWUiOjE3MTE3MTMzNTksInVzZXJfaWQiOiJWS2lIWkZIZWNyZEhZRnVVaE94eVlsODBuZmoyIiwic3ViIjoiVktpSFpGSGVjcmRIWUZ1VWhPeHlZbDgwbmZqMiIsImlhdCI6MTcxMTcxMzM1OSwiZXhwIjoxNzExNzE2OTU5LCJlbWFpbCI6ImFkbWluQGdtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhZG1pbkBnbS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.jGRKhq-P9Y4f43lrQOlZOGTCjxHFketETlH3Ba8nNJGE_DYJsAfZV11h3Oo0VIN-eFRCkFxAgEYpuSt3SBEaHwXHARKeizirNbWR0Gf-jis2neh9uZ0vdzWV2GC6yLHvPoPZ4TCabWrXvXkLoJUU-SpaE1HxsqyWJ8q9fIsBbB0ljMpKfaQr-KJZMtxcaXvEpHxV_DIfYmFvQL2KJAGRN-JC2MI6XRgZzk9gNqtu1hlUHk0_Lrck8nWdnRL0w8JLS3K8OUi64T9ag3h-GKZySL1Qi_pwp5xbuHuPaYnQCXlIjrMTd8V4cNNyNw4jhyWuDo5lkfN461QGC_XJ3-5-Rg

{
   "date": "2023-10-05",
   "registerNo":"6605e5b628fe2c3b1cc0fa1a",
   "time":"08.55"
}

#### get
GET http://localhost:8080/clinic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aGFwcC1jMWY4NiIsImF1ZCI6ImF1dGhhcHAtYzFmODYiLCJhdXRoX3RpbWUiOjE3MTE3MTMzNTksInVzZXJfaWQiOiJWS2lIWkZIZWNyZEhZRnVVaE94eVlsODBuZmoyIiwic3ViIjoiVktpSFpGSGVjcmRIWUZ1VWhPeHlZbDgwbmZqMiIsImlhdCI6MTcxMTcxMzM1OSwiZXhwIjoxNzExNzE2OTU5LCJlbWFpbCI6ImFkbWluQGdtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhZG1pbkBnbS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.jGRKhq-P9Y4f43lrQOlZOGTCjxHFketETlH3Ba8nNJGE_DYJsAfZV11h3Oo0VIN-eFRCkFxAgEYpuSt3SBEaHwXHARKeizirNbWR0Gf-jis2neh9uZ0vdzWV2GC6yLHvPoPZ4TCabWrXvXkLoJUU-SpaE1HxsqyWJ8q9fIsBbB0ljMpKfaQr-KJZMtxcaXvEpHxV_DIfYmFvQL2KJAGRN-JC2MI6XRgZzk9gNqtu1hlUHk0_Lrck8nWdnRL0w8JLS3K8OUi64T9ag3h-GKZySL1Qi_pwp5xbuHuPaYnQCXlIjrMTd8V4cNNyNw4jhyWuDo5lkfN461QGC_XJ3-5-Rg
