### User Creation Request
POST http://localhost:8080/medical
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aGFwcC1jMWY4NiIsImF1ZCI6ImF1dGhhcHAtYzFmODYiLCJhdXRoX3RpbWUiOjE3MTE3MDk2OTEsInVzZXJfaWQiOiJWS2lIWkZIZWNyZEhZRnVVaE94eVlsODBuZmoyIiwic3ViIjoiVktpSFpGSGVjcmRIWUZ1VWhPeHlZbDgwbmZqMiIsImlhdCI6MTcxMTcwOTY5MSwiZXhwIjoxNzExNzEzMjkxLCJlbWFpbCI6ImFkbWluQGdtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhZG1pbkBnbS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.CIjZ3T-SnNcXj79rlJ1ENTgR4aoGR6AMJTYMHA9AiPZXuKdHRXYzudyoJH_iaIfvfeat7KYBW7tX2gydsn-PfLccV628vg2zzoSaedI9sg6D0FOaDr-BU8CcqScOGjJWHlYKo4oaLGqYOhlUUWq2v4KnR4AyNlKgGSi4hjcJ1B8m4hOEwZtl0IT7EHY8w_TFKPFXNZvnDNVFiCn7zAqAFppbME7CIUDsodDRNYE4bSA2VpTDKPhNBopu4B4yO2zYAzjDll8im2SEG8o3vsGNJkiZEqGTk3es-tAWSKbFlP42-agXeJvQx7QTOY6woKyjsdOY5vntrH6qrLLrB-z9yg

{
   "date": "2023-10-05",
   "registerNo":"CH0002",
   "medicalOfficerID": "MED001",
   "medicalOfficerName": "Medical Officer2",
   "details": "Lorem Ipsum is simply dummy text of the printing"
}

#### get
GET http://localhost:8080/medical
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aGFwcC1jMWY4NiIsImF1ZCI6ImF1dGhhcHAtYzFmODYiLCJhdXRoX3RpbWUiOjE3MTE3MDk2OTEsInVzZXJfaWQiOiJWS2lIWkZIZWNyZEhZRnVVaE94eVlsODBuZmoyIiwic3ViIjoiVktpSFpGSGVjcmRIWUZ1VWhPeHlZbDgwbmZqMiIsImlhdCI6MTcxMTcwOTY5MSwiZXhwIjoxNzExNzEzMjkxLCJlbWFpbCI6ImFkbWluQGdtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhZG1pbkBnbS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.CIjZ3T-SnNcXj79rlJ1ENTgR4aoGR6AMJTYMHA9AiPZXuKdHRXYzudyoJH_iaIfvfeat7KYBW7tX2gydsn-PfLccV628vg2zzoSaedI9sg6D0FOaDr-BU8CcqScOGjJWHlYKo4oaLGqYOhlUUWq2v4KnR4AyNlKgGSi4hjcJ1B8m4hOEwZtl0IT7EHY8w_TFKPFXNZvnDNVFiCn7zAqAFppbME7CIUDsodDRNYE4bSA2VpTDKPhNBopu4B4yO2zYAzjDll8im2SEG8o3vsGNJkiZEqGTk3es-tAWSKbFlP42-agXeJvQx7QTOY6woKyjsdOY5vntrH6qrLLrB-z9yg
