### User Creation Request
POST http://localhost:8080/vaccine
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aGFwcC1jMWY4NiIsImF1ZCI6ImF1dGhhcHAtYzFmODYiLCJhdXRoX3RpbWUiOjE3MTE3MTkzMDAsInVzZXJfaWQiOiJWS2lIWkZIZWNyZEhZRnVVaE94eVlsODBuZmoyIiwic3ViIjoiVktpSFpGSGVjcmRIWUZ1VWhPeHlZbDgwbmZqMiIsImlhdCI6MTcxMTcxOTMwMCwiZXhwIjoxNzExNzIyOTAwLCJlbWFpbCI6ImFkbWluQGdtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhZG1pbkBnbS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Zpy8uGRMrzhnemiMvqH_kgIy9U91Ax59zcIoomqrfH09qeLJ6k9CeLsWCX1Bmp92_d5fv80D4n0iQK1MYWExo3R_aUcW0l_YZgTA5Mlqknoe7QM_2Ov9P72G-6C_CeuL4J7R_qc2uyFVpFUg9FX1bUiapoGdV8aw0PYpQfySX6I9fa9s4meNkqAN5U0VSlD-qKVrmgrobIMVfDrZixC42ouWS_iaR3rajz4nIjLyr47sG_xuuOpset5ZDwwePJLoY4XXNJjDYWYM0HBXdq1VpODbJkLlsDNi8tGmsmAnVB_ES_g5g4we6sdWTrkRZU5G0dxf8DZMALuJIU-6GEC53A

{
   "registerNo": "CH0001",
   "date": "2023-10-05",
   "name":"VACREC002",
   "time":"08.55",
   "batchNo": "VACBAT002",
   "age": 2,
   "details": "Lorem Ipsum is simply dummy text of the printing"
}

#### get
GET http://localhost:8080/vaccine
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImJhNjI1OTZmNTJmNTJlZDQ0MDQ5Mzk2YmU3ZGYzNGQyYzY0ZjQ1M2UiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aGFwcC1jMWY4NiIsImF1ZCI6ImF1dGhhcHAtYzFmODYiLCJhdXRoX3RpbWUiOjE3MTE3MTkzMDAsInVzZXJfaWQiOiJWS2lIWkZIZWNyZEhZRnVVaE94eVlsODBuZmoyIiwic3ViIjoiVktpSFpGSGVjcmRIWUZ1VWhPeHlZbDgwbmZqMiIsImlhdCI6MTcxMTcxOTMwMCwiZXhwIjoxNzExNzIyOTAwLCJlbWFpbCI6ImFkbWluQGdtLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJhZG1pbkBnbS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Zpy8uGRMrzhnemiMvqH_kgIy9U91Ax59zcIoomqrfH09qeLJ6k9CeLsWCX1Bmp92_d5fv80D4n0iQK1MYWExo3R_aUcW0l_YZgTA5Mlqknoe7QM_2Ov9P72G-6C_CeuL4J7R_qc2uyFVpFUg9FX1bUiapoGdV8aw0PYpQfySX6I9fa9s4meNkqAN5U0VSlD-qKVrmgrobIMVfDrZixC42ouWS_iaR3rajz4nIjLyr47sG_xuuOpset5ZDwwePJLoY4XXNJjDYWYM0HBXdq1VpODbJkLlsDNi8tGmsmAnVB_ES_g5g4we6sdWTrkRZU5G0dxf8DZMALuJIU-6GEC53A